### PR TITLE
Added logos.

### LINKED ISSUE #7: Logo for Open Imagery Network
We need a logo for Open Imagery Network.

@designmatty has done these logo explorations:
logo1
logo2
logo3

Does anyone have feedback or preferences?

### PR DESCRIPTION
**Pull request by lossyrob**
Credit: Matt Williams (@designmatty)

Closes #7 

logo
logo-with-text

### CODE REVIEW

**Comment by lossyrob** [comment]
Closes #7

**Comment by designmatty** [comment]
I'll make sure to provide the vector formats in the coming days.

**Comment by cgiovando** [comment]
Looks great, love the concept, thanks @designmatty!

Wondering if we should try to abstract the earth representation a bit, for example with a standard lat/lon graticule or just rotate it on a more common longitude view.

I mean, I like the Pacific ocean view, but on a smaller size logo version it may not be obvious that the white spot above the wing is Papua and the upper slivers are north America and east Asia.

Plus, the ocean is probably the area with least images in OIN :-)

**Comment by smit1678** [comment]
@designmatty Picking this back up. Do you still have the vector versions of the logo we can drop in here? I can then merge that in.

**Comment by designmatty** [comment]
@smit1678 Yup! Here it is.

[OIN-Logo.zip](https://github.com/openimagerynetwork/oin-register/files/415619/OIN-Logo.zip)

**Comment by designmatty** [comment]
I also took the feedback from @cgiovando about abstracting the earth and included that version along with the original in the zip.

**Comment by smit1678** [comment]
👍  nice, I dig it. Thanks.

**Comment by designmatty** [comment]
No Problem.

**Pull request merged**
